# NumPy
Python does not have arrays traditionally and numpy library lets us make arrays but it is treated a little differently. It forms the basis of Data Science and other libraries like pandas, tensorflow, pytorch etc.  


## Introduction
Vector = 1D array  
Matrix = 2D array  
Tensor = nD array (3D and above, but includes 1D and 2D as special cases)

In [1]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(f"1D array: {arr_1d}")
arr_2d = np.array([[1,2,3],[4,5,6]])
print(f"2D array: {arr_2d}")

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list = [1,2,3]
print(f"Python List multiplication by 2 : {2*py_list}")
np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication ", np_array*2)

Python List multiplication by 2 : [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [5]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.03745675086975098

 Numpy operation time:  0.0050449371337890625


### Creating Arrays from Scratch

In [6]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
full = np.full((1,2),7)
print(full)

[[7 7]]


In [ ]:
random = np.random.random((6,7))
print(random) # random values are between 0 and 1

[[0.07602213 0.77017218 0.40715318 0.44859948 0.09766475 0.07843842
  0.88165014]
 [0.51481285 0.9874665  0.07886132 0.66893089 0.09282959 0.51475269
  0.98584647]
 [0.56963529 0.48947741 0.03518636 0.79201325 0.60504681 0.48878479
  0.12668682]
 [0.58757449 0.52116117 0.18873929 0.35132317 0.45014289 0.34730213
  0.08576242]
 [0.76563452 0.60953073 0.0770954  0.34192917 0.63091316 0.65186484
  0.70288258]
 [0.54277616 0.70216791 0.35829239 0.13519231 0.30261126 0.55913403
  0.58673633]]


In [12]:
sequence = np.arange(0,10,2) # (initial value, final value, step)
print(sequence) # Range in Python is always non inclusive outer boundary, that means the stop or the final value is never included

[0 2 4 6 8]


### Vector, Matrix, Tensor

In [13]:
vector = np.array ([1,2,3])
print(vector)

[1 2 3]


In [14]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [15]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # row x columns
print(arr.ndim) # Dimensions
print(arr.size) # Size - total elements
print(arr.dtype) # Data type of elements - if even one element is float, the data type of array would be float etc,

(2, 3)
2
6
int64


#### Array Reshaping

In [19]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
reshaped = arr.reshape((3,4))
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
flattened = reshaped.flatten()
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
raveled = reshaped.ravel()
print(raveled) # Returns view, instead of copy

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
transpose = reshaped.T
print(transpose)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Operations on Numpy Arrays

In [1]:
import numpy as np

### Slicing

In [ ]:
arr = np.arange(1,11,1)
print(arr[2:7]) # Slicing - returns new array from index 2 to 6
print(arr[1:8:2]) # Slicing with 2 step
print(arr[-3]) # From the end 3rd element

[3 4 5 6 7]
[2 4 6 8]
8


In [ ]:
# Slicing in 2D array
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[1,2]) # Based on zero indexing, 1st row 2nd element which is second row, third element
print(arr_2d[1]) # Entire row
print(arr_2d[:,1]) # Take all rows but only one column == array[row_selection , column_selection]

### Sorting

In [ ]:
unsorted = np.array([3,1,4,5,6,1,3])
print(np.sort(unsorted)) # Basic Sorting function
arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print(np.sort(arr_2d_unsorted, axis=0)) # Column wise sorting
'''
Case 1: axis=0 → sort each column independently
Case 2: axis=1 → sort each row independently
'''

[1 1 3 3 4 5 6]
[[1 1]
 [2 2]
 [3 3]]


### Filter

In [6]:
numbers = np.arange(1,11,1)
even_number = numbers[numbers % 2 == 0]
print(even_number)

[ 2  4  6  8 10]


In [7]:
# Filter with mask
mask = numbers > 5
print(numbers[mask])

[ 6  7  8  9 10]


### Fancy Indexing and np,where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [ ]:
where_result = np.where(numbers>5)
print(where_result)
print(numbers[where_result])
'''
Case 1: One-argument form
Here np.where(condition) returns the indices (positions) where the condition is True.
'''

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
print(condition_array)
'''
Case 2: Three-argument form
np.where(condition, if true, else false)
'''

[ 1  2  3  4  5 12 14 16 18 20]


### Merging two arrays

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2) # Returns [5,7,9]
combined = np.concatenate((arr1,arr2)) # np.concatenate expects a single argument: a sequence of arrays (like a list or tuple).
print(combined)

[5 7 9]
[1 2 3 4 5 6]


In [13]:
# Array Compatibility = shape should be same
print(arr1.shape == arr2.shape)

True


In [16]:
# Adding a row or a column in Arrays

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]]) # new_row must match the number of columns (2 in this case).

with_new_row = np.vstack((original, new_row)) # Verticle Stack adds a new row, before [[]] after [[],
                                                                                                # []]
# print(original)
print(with_new_row)

new_col = np.array([[7], [8]]) # new_col must match the number of rows (2 in this case).
with_new_col = np.hstack((original, new_col)) # Horizontal Stack adds a new column, a new element inside each row
                                              # Before [[1],[2]], after [[1,3],[2,4]]
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [17]:
# Deleting element
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2) # Does not return the deleted element, returns remaining array after deleting the element
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
